name: Build and Deploy Next.js project
# Sets permissions of the GITHUB_TOKEN to allow deployment
permissions:
  contents: read

# Controls when the workflow will run
on:
  # Triggers the action only when files change in the folders defined here
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install all NPM dependencies and build storybook as a static files
      - name: Install Packages and Build Next.js project
        run: |
          npm install
          npm run build

      # Deploy project
      - name: Deploy Next.js project
        run: echo "✔ Project is ready for deploy"
